# Generated by Django 2.1.5 on 2020-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_info', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
